# Generated by Django 5.2.5 on 2025-08-10 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eskul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_eskul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pelatih', models.ForeignKey(limit_choices_to={'role': 'pelatih'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pertemuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('materi_kegiatan', models.TextField()),
                ('foto_kegiatan', models.ImageField(blank=True, null=True, upload_to='kegiatan/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertemuan_list', to='eskul.eskul')),
                ('pelatih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_siswa', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=10)),
                ('no_induk', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eskul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa_list', to='eskul.eskul')),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hadir', models.BooleanField(default=False)),
                ('keterangan', models.CharField(choices=[('hadir', 'Hadir'), ('sakit', 'Sakit'), ('izin', 'Izin'), ('alpha', 'Alpha')], default='alpha', max_length=20)),
                ('pertemuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi_list', to='eskul.pertemuan')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eskul.siswa')),
            ],
            options={
                'unique_together': {('pertemuan', 'siswa')},
            },
        ),
    ]
