# Generated by Django 5.2.5 on 2025-08-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eskul', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='siswa',
            unique_together={('nama_siswa', 'kelas')},
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='no_induk',
        ),
    ]
