# Generated by Django 5.2.5 on 2025-08-10 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskul', '0002_alter_siswa_unique_together_remove_siswa_no_induk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pertemuan',
            unique_together={('eskul', 'tanggal')},
        ),
        migrations.CreateModel(
            name='FotoKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='kegiatan/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pertemuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_list', to='eskul.pertemuan')),
            ],
        ),
        migrations.RemoveField(
            model_name='pertemuan',
            name='foto_kegiatan',
        ),
    ]
