# Generated by Django 5.2.5 on 2025-08-10 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eskul', '0003_alter_pertemuan_unique_together_fotokegiatan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eskul',
            name='pelatih',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'pelatih'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
