# Generated by Django 5.2.5 on 2025-10-03 14:55

from django.db import migrations


def create_default_eskul_data(apps, schema_editor):
    Eskul = apps.get_model('eskul', 'Eskul')

    default_eskul_data = [
        {
            'nama_eskul': 'Tahfidz',
            'deskripsi': 'Kegiatan menghafal Al-Qur\'an untuk meningkatkan keimanan dan ketakwaan kepada Allah SWT.',
            'is_active': True
        },
        {
            'nama_eskul': 'Vokal',
            'deskripsi': 'Kegiatan pelatihan vokal untuk mengembangkan bakat menyanyi dan kemampuan vocal siswa.',
            'is_active': True
        },
        {
            'nama_eskul': 'Pencak Silat',
            'deskripsi': 'Seni bela diri tradisional Indonesia untuk melatih fisik, mental, dan disiplin siswa.',
            'is_active': True
        },
        {
            'nama_eskul': 'Futsal',
            'deskripsi': 'Olahraga sepak bola mini untuk mengembangkan kemampuan teknik, fisik, dan kerja sama tim.',
            'is_active': True
        },
        {
            'nama_eskul': 'Angklung',
            'deskripsi': 'Kegiatan musik tradisional dengan alat musik angklung untuk melestarikan budaya Sunda.',
            'is_active': True
        },
        {
            'nama_eskul': 'Tari',
            'deskripsi': 'Kegiatan seni tari untuk mengembangkan bakat menari dan apresiasi seni budaya.',
            'is_active': True
        },
        {
            'nama_eskul': 'Pramuka',
            'deskripsi': 'Kegiatan kepramukaan untuk membentuk karakter kepemimpinan, kemandirian, dan cinta alam.',
            'is_active': True
        },
    ]

    for eskul_data in default_eskul_data:
        Eskul.objects.get_or_create(
            nama_eskul=eskul_data['nama_eskul'],
            defaults=eskul_data
        )


class Migration(migrations.Migration):

    dependencies = [
        ('eskul', '0004_alter_eskul_pelatih'),
    ]

    operations = [
        migrations.RunPython(create_default_eskul_data),
    ]
